version: "3.8"
services:
  cache:
    container_name: "redis-cache"
    image: "redis:latest"
    expose:
      - "6379"
  api:
    container_name: "api"
    build:
      context: "."
    command: bash -c "/wait && python -m flask run --host=0.0.0.0"
    volumes:
      - "./:/app"
    depends_on:
      - "cache"
    environment:
      - "API_KEY=${API_KEY}"
      - "WAIT_HOSTS=redis-cache:6379"
      - "FLASK_ENV=development"
    ports:
      - "5000:5000"
